controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001

planner_server:
  ros__parameters:
    use_sim_time: False

local_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    plugins: ["voxel_layer", "inflation_layer"]
    voxel_layer:
      enabled: True
      topic: "/zed2/point_cloud/cloud_registered"
      max_obstacle_height: 2.0
      origin_z: 0.0
      z_resolution: 0.05
      z_voxels: 40

global_costmap:
  ros__parameters:
    update_frequency: 1.0
    publish_frequency: 1.0